import { getTenantDb, getTenantSchemaName } from "./client";
import { sql } from "drizzle-orm";
import fs from "fs";
import path from "path";

export async function migrateNewTenant(tenantId: string) {
  const schemaName = getTenantSchemaName(tenantId);
  const tenantDb = getTenantDb(schemaName);

  // 1. Create the schema
  await tenantDb.execute(sql.raw(`CREATE SCHEMA IF NOT EXISTS "${schemaName}";`));
  // Set search_path for the current session explicitly just in case
  await tenantDb.execute(sql.raw(`SET search_path TO "${schemaName}", public;`));

  // 2. Read the latest migration file
  // In a real production app with multiple migrations, you'd want a proper migrator.
  // For now, we run the initial migration file.
  const migrationsDir = path.join(process.cwd(), "src/database/migrations/tenant");
  const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith(".sql")).sort();

  for (const file of files) {
    let content = fs.readFileSync(path.join(migrationsDir, file), "utf-8");
    // Remove "public". prefixes generated by Drizzle for foreign keys and enums
    // so they are created in the current search_path (the tenant schema)
    content = content.replace(/"public"\./g, "");
    
    // Split by statement breakpoints if Drizzle uses them
    const statements = content.split("--> statement-breakpoint");
    for (const stmt of statements) {
      if (stmt.trim()) {
        try {
          await tenantDb.execute(sql.raw(stmt.trim()));
        } catch (err: any) {
          // Ignore if relation already exists (e.g. if we run this multiple times)
          if (!err.message.includes("already exists")) {
            console.error(`Error executing statement: ${stmt}`, err);
            throw err;
          }
        }
      }
    }
  }
}
